module: Yams
author: JP Simard, Norio Nomura
author_url: http://jpsim.com
github_url: https://github.com/jpsim/Yams
github_file_prefix: https://github.com/jpsim/Yams/tree/docs

swift_version: 4.0
theme: fullwidth
clean: true
copyright: '© 2017 [JP Simard](http://jpsim.com) under MIT.'
